"""Machine-readable Profile 2.0 execution contract.

Values are intentionally limited to supported/partial/unsupported so tests and
documentation can detect fields that would otherwise be silently ignored.
"""

STYLE_FIELD_CAPABILITIES = {
    "font.east_asia": "supported",
    "font.latin": "supported",
    "font.complex_script": "partial",
    "size": "supported",
    "bold": "supported",
    "italic": "supported",
    "alignment": "supported",
    "first_line_indent_chars": "supported",
    "hanging_indent_chars": "supported",
    "line_spacing": "supported",
    "space_before_pt": "supported",
    "space_after_pt": "supported",
    "keep_with_next": "supported",
    "pagination": "unsupported",
    "numbering": "unsupported",
    "separator": "unsupported",
    "prefix": "unsupported",
    "suffix": "unsupported",
    "provenance": "supported",
    "confidence": "supported",
    "source_kind": "supported",
    "candidates": "supported",
}

PROFILE_FIELD_CAPABILITIES = {
    "profile_version": "supported",
    "profile_status": "supported",
    "approved_at": "supported",
    "journal": "supported",
    "document.page_size": "supported",
    "document.margins": "supported",
    "document.text_color": "partial",
    "document.line_spacing": "supported",
    "title.default": "supported",
    "title.zh": "partial",
    "title.en": "partial",
    "abstract.*.label": "supported",
    "abstract.*.body": "supported",
    "abstract.*.count": "supported",
    "keywords.*.label": "supported",
    "keywords.*.body": "supported",
    "keywords.*.count": "supported",
    "keywords.*.separator": "supported",
    "anonymous_review.hide_authors": "supported",
    "anonymous_review.hide_affiliations": "supported",
    "anonymous_review.hide_funding": "supported",
    "anonymous_review.hide_email": "supported",
    "anonymous_review.hide_orcid": "supported",
    "anonymous_review.hide_correspondence": "supported",
    "anonymous_review.hide_acknowledgements": "partial",
    "citation.default_mode": "supported",
    "citation.bibliography": "supported",
    "citation.csl": "supported",
    "citation.zotero_style": "supported",
    "citation.locale": "supported",
    "citation.allow_csl_m_static": "supported",
    "output.reference_docx": "supported",
    "output.filename_pattern": "supported",
    "obsidian.attachment_paths": "supported",
}
